import type { Settings } from '../settings.ts';

export interface Preset {
  name: string;
  description: string;
  settings: Partial<Settings>;
}

export const PRESETS: Preset[] = [
  {
    name: 'Classic Flock',
    description: 'Balanced Reynolds boids — clear separation, alignment, and cohesion.',
    settings: {
      mode3D: true,
      boidCount: 1500,
      visionRadius: 60,
      movementAccuracy: 20,
      alignmentForce: 1.2,
      cohesionForce: 1.0,
      separationForce: 1.5,
      steeringForce: 0.5,
      minSpeed: 1.5,
      maxSpeed: 4.5,
      drag: 0.02,
      randomness: 0.08,
      bounceEdges: true,
      particleMode: false,
      worldDepth: 800,
      collisionRadius: 12,
      collisionForce: 3.0,
      boidSize: 1.5,
      backgroundColor: '#0a0a1a',
      boidColor: '#88ccff',
      hueBySpeed: false,
    },
  },
  {
    name: 'Starling Murmuration',
    description: 'Dense, tightly-coupled flock with strong alignment — mimics starling murmurations.',
    settings: {
      mode3D: true,
      boidCount: 3000,
      visionRadius: 45,
      movementAccuracy: 7,
      alignmentForce: 2.4,
      cohesionForce: 1.8,
      separationForce: 1.2,
      steeringForce: 0.7,
      minSpeed: 2.0,
      maxSpeed: 5.5,
      drag: 0.015,
      randomness: 0.15,
      bounceEdges: true,
      particleMode: false,
      worldDepth: 600,
      collisionRadius: 6,
      collisionForce: 2.0,
      boidSize: 1.0,
      backgroundColor: '#050510',
      boidColor: '#aaddff',
      hueBySpeed: true,
    },
  },
  {
    name: 'Fish School',
    description: '2D school with wide vision, slow speed, and strong cohesion — like a shoal of fish.',
    settings: {
      mode3D: false,
      boidCount: 2000,
      visionRadius: 80,
      movementAccuracy: 12,
      alignmentForce: 0.8,
      cohesionForce: 2.0,
      separationForce: 1.8,
      steeringForce: 0.35,
      minSpeed: 0.8,
      maxSpeed: 3.0,
      drag: 0.04,
      randomness: 0.05,
      bounceEdges: true,
      particleMode: false,
      worldDepth: 800,
      collisionRadius: 15,
      collisionForce: 4.0,
      boidSize: 1.2,
      backgroundColor: '#0a1520',
      boidColor: '#44aacc',
      hueBySpeed: false,
    },
  },
  {
    name: 'Insect Swarm',
    description: 'High randomness, weak alignment — chaotic swarm with emergent clustering.',
    settings: {
      mode3D: true,
      boidCount: 2500,
      visionRadius: 35,
      movementAccuracy: 10,
      alignmentForce: 0.3,
      cohesionForce: 0.6,
      separationForce: 2.0,
      steeringForce: 0.8,
      minSpeed: 1.0,
      maxSpeed: 6.0,
      drag: 0.01,
      randomness: 0.6,
      bounceEdges: true,
      particleMode: false,
      worldDepth: 500,
      collisionRadius: 8,
      collisionForce: 2.5,
      boidSize: 0.8,
      backgroundColor: '#0f0f05',
      boidColor: '#ccdd44',
      hueBySpeed: true,
    },
  },
  {
    name: 'Tight Formation',
    description: 'Very strong cohesion and separation, low randomness — boids form dense orderly groups.',
    settings: {
      mode3D: true,
      boidCount: 800,
      visionRadius: 100,
      movementAccuracy: 32,
      alignmentForce: 2.0,
      cohesionForce: 2.5,
      separationForce: 2.5,
      steeringForce: 0.4,
      minSpeed: 1.0,
      maxSpeed: 3.5,
      drag: 0.03,
      randomness: 0.02,
      bounceEdges: true,
      particleMode: false,
      worldDepth: 600,
      collisionRadius: 18,
      collisionForce: 5.0,
      boidSize: 2.0,
      backgroundColor: '#0a0a1a',
      boidColor: '#ff8866',
      hueBySpeed: false,
    },
  },
  {
    name: 'Particle Dust',
    description: 'Flocking forces off — pure particle drift with noise and drag. Click to interact.',
    settings: {
      mode3D: true,
      boidCount: 4000,
      visionRadius: 50,
      movementAccuracy: 16,
      alignmentForce: 0,
      cohesionForce: 0,
      separationForce: 0,
      steeringForce: 0.5,
      minSpeed: 0.2,
      maxSpeed: 3.0,
      drag: 0.005,
      randomness: 0.4,
      bounceEdges: false,
      particleMode: true,
      worldDepth: 1000,
      collisionRadius: 0,
      collisionForce: 0,
      boidSize: 0.6,
      backgroundColor: '#000000',
      boidColor: '#ffffff',
      hueBySpeed: true,
    },
  },
  {
    name: 'High Speed Chase',
    description: 'Fast boids with strong separation — looks like a high-speed aerial chase.',
    settings: {
      mode3D: true,
      boidCount: 1200,
      visionRadius: 70,
      movementAccuracy: 16,
      alignmentForce: 1.5,
      cohesionForce: 0.5,
      separationForce: 2.5,
      steeringForce: 1.0,
      minSpeed: 3.0,
      maxSpeed: 9.0,
      drag: 0.01,
      randomness: 0.2,
      bounceEdges: true,
      particleMode: false,
      worldDepth: 1200,
      collisionRadius: 14,
      collisionForce: 4.0,
      boidSize: 1.8,
      backgroundColor: '#0a0a1a',
      boidColor: '#ff4466',
      hueBySpeed: true,
    },
  },
];

export function applyPreset(preset: Preset, target: Settings): void {
  Object.assign(target, preset.settings);
}
